### ISSUE TITLE
Help: What are differences between Middleware, Plugin and Decorator?

### ISSUE THREAD

**Issue by kitepad** [fastrojs/fastro-server#2]
Would you give more descriptions about their best usage scenario? I have some confuse about which scenario is best.

**Comment by ynwd** [comment]
Middleware is used only for certain URLs. (default is /. add another url if you need). 

decorator is used for urls globally. 

The plugin is used to combine several routers, middleware, or decorators that have special requirement in one module. This is useful if you have several plugins. You can give a prefix to distinguish it.
